Created services to login and register, and integrated them to backen…
EsMACGIA/alumnusb-gamification-frontend pull request #2
Opened 2021-01-30 22:05 UTC by jaoc1811

…d api

### Please read and mark the following check list before creating a pull request (check one with "x"):

 - [ ] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/ngx-admin/blob/master/CONTRIBUTING.md) guide.
 - [ ] I read and followed the [New Feature Checklist](https://github.com/akveo/ngx-admin/blob/master/DEV_DOCS.md#new-feature-checklist) guide.
 
 #### Short description of what this resolves:

2021-02-01 13:42 UTC, mfaria724 requested changes
Son tonterías, pero arréglalas. Especialmente las vainas comentadas.

2021-02-01 13:42 UTC, mfaria724 commented on README.md
> +- On the root folder where `Dockerfile` file is located, run the following command:
Good catch!

2021-02-01 13:42 UTC, mfaria724 commented on src/app/auth/auth.service.ts
> +      // this.currentUserSubject = new BehaviorSubject<any>(JSON.parse(localStorage.getItem('currentUser')));
¿Por qué esto está comentado?

Si no es necesario, quítenlo.

2021-02-01 13:42 UTC, mfaria724 commented on src/app/auth/auth.service.ts
> +    // localStorage.removeItem('currentUser');
Este creo que ni siquiera lo tengo que explicar.

2021-02-01 13:42 UTC, mfaria724 commented on src/app/auth/models/login.model.ts
> +}
Fíjate en este tipo de vainas, que hasta GitHub las marca como errores. Es buena práctica dejar una línea en blanco al final de los archivos. Creo que te lo mencioné previamente en otro CR (O capáz fue a otro del equipo).

2021-02-06 23:58 UTC, jaoc1811 commented on src/app/auth/auth.service.ts
> +      // this.currentUserSubject = new BehaviorSubject<any>(JSON.parse(localStorage.getItem('currentUser')));
Esto va a ser usado en un futuro

2021-02-06 23:58 UTC, jaoc1811 commented on src/app/auth/auth.service.ts
> +    // localStorage.removeItem('currentUser');
Misma razon

2021-02-07 00:11 UTC, jaoc1811 commented on src/app/auth/models/login.model.ts
> +}
listo

2021-02-07 19:23 UTC, mfaria724 approved these changes
Ship it!

2021-02-07 19:24 UTC, merged