Added achievements page
EsMACGIA/alumnusb-gamification-frontend pull request #4
Opened 2021-02-08 01:59 UTC by CarlosRivero96

![achievements](https://user-images.githubusercontent.com/32308116/107167602-a9815f80-698f-11eb-8c34-ca3a71c93c47.png)
### Please read and mark the following check list before creating a pull request (check one with "x"):

 - [ ] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/ngx-admin/blob/master/CONTRIBUTING.md) guide.
 - [ ] I read and followed the [New Feature Checklist](https://github.com/akveo/ngx-admin/blob/master/DEV_DOCS.md#new-feature-checklist) guide.
 
 #### Short description of what this resolves:

2021-02-08 10:36 UTC, mfaria724 requested changes
Está burda de bien en verdad. Me gustó que hayan creado un móduo a parte porque tenían que crear un nuevo servicio.

Traten de pensar un pelo en futuros desarrolladores. Son cosas full idiotas como un espacio o una coma, pero si empiezas a dejar todo "sucio" por ahí, cunado te das cuenta tienes un chiquero de código.

Arreglen eso y lo veo todo bien para mergear..

2021-02-08 10:36 UTC, mfaria724 commented on src/app/pages/achievements/Achievements.model.ts
> +class Achieved {
Puedes crear una sola clase, y colocar la fecha como opcional.

```typescript
class MyClass {
   att1: string; // required
   att2?: string; // can be null
}
```

2021-02-08 10:36 UTC, mfaria724 commented on src/app/pages/achievements/achievements.component.html
> +</div>
Siempre línea al final del archivo.

2021-02-08 10:36 UTC, mfaria724 commented on src/app/pages/achievements/achievements.component.html
> +  <div class="col-md-12 col-lg-6 col-xxxl-6">
Siempre comenta las secciones, si esto crece se pone horrible leerlo sin comentarios.

2021-02-08 10:36 UTC, mfaria724 commented on src/app/pages/achievements/achievements.component.scss
> +  .achievement {
Deja líneas en blaco para hacer esto un poco más legible.

2021-02-08 10:36 UTC, mfaria724 commented on src/app/pages/achievements/achievements.component.ts
> +
Línea de más.

2021-02-08 10:36 UTC, mfaria724 commented on src/app/pages/achievements/achievements.component.ts
> +  data = {
Un comentario explicando por qué esto es necesario. Yo lo entiendo porque tengo contexto, pero piensa en futuros dev (O los pobres desdichadosque agarrarán esta vaina en sistemas 3).

2021-02-08 10:36 UTC, mfaria724 commented on src/app/pages/achievements/achievements.module.ts
> +
Línea de más.

2021-02-08 10:36 UTC, mfaria724 commented on src/app/pages/achievements/achievements.service.ts
> +}
Simetría. O usa una línea antes de terminar la clase, o quita la del inicio.

2021-02-08 10:36 UTC, mfaria724 commented on src/app/pages/pages.module.ts
> +
Línea de más.

2021-02-17 21:00 UTC, CarlosRivero96 commented on src/app/pages/achievements/achievements.component.html
> +  <div class="col-md-12 col-lg-6 col-xxxl-6">
Los tags se sacaron directamente del template

2021-02-17 21:01 UTC, CarlosRivero96 commented on src/app/pages/achievements/achievements.component.ts
> +  data = {
Esto es temporal mientras usamos dummy data

2021-02-17 23:24 UTC, mfaria724 approved these changes
Brutal!

2021-02-17 23:24 UTC, merged